// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TripPlanner.Models;

namespace TripPlanner.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20191212200640_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TripPlanner.Models.Tourist", b =>
                {
                    b.Property<int>("TouristId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("JoiningTripId");

                    b.Property<int>("TravellerId");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("TouristId");

                    b.HasIndex("JoiningTripId");

                    b.HasIndex("TravellerId");

                    b.ToTable("Tourists");
                });

            modelBuilder.Entity("TripPlanner.Models.Trip", b =>
                {
                    b.Property<int>("TripId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Destination")
                        .IsRequired();

                    b.Property<DateTime>("EndDate");

                    b.Property<string>("Plan")
                        .IsRequired();

                    b.Property<int>("PlannerId");

                    b.Property<DateTime>("StartDate");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("TripId");

                    b.HasIndex("PlannerId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("TripPlanner.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TripPlanner.Models.Tourist", b =>
                {
                    b.HasOne("TripPlanner.Models.Trip", "JoiningTrip")
                        .WithMany("Tourists")
                        .HasForeignKey("JoiningTripId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TripPlanner.Models.User", "Traveller")
                        .WithMany("JoiningTrips")
                        .HasForeignKey("TravellerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TripPlanner.Models.Trip", b =>
                {
                    b.HasOne("TripPlanner.Models.User", "Planner")
                        .WithMany("createdPlans")
                        .HasForeignKey("PlannerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
